development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: antorcha_development
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

# test: &test
#   adapter: mysql
#   encoding: utf8
#   reconnect: false
#   database: antorcha_test
#   pool: 5
#   username: root
#   password:
#   socket: /tmp/mysql.sock

test: &test
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: antorcha_production
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

cucumber:
  <<: *test